[package]
name = "tmax-git"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
git2.workspace = true
serde.workspace = true

[dev-dependencies]
tempfile.workspace = true
